### Where things are

# collections:  null
#   - a_collection


### Handling Reading

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '*org'
  - '*~'
  - '#*'
  - '.#*'

### Filtering Content

future: false

### Plugins

# whitelist: []
# gems:      []


### Conversion

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
excerpt_separator: "<!-- more -->"


### Serving

url: http://wobh.github.io

### Outputting

permalink: date
# paginate: 12
timezone: America/Detroit
