title: WOBH
email: wobh@yahoo.com
description: >-
  Idle thoughts from an idle fellow

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# url: http://wobh.github.io
twitter_username: wobher
github_username:  wobh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# whitelist: []
# gems:      []

### Handling Reading
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - "*org"
  - "*~"
  - "#*"
  - ".#*"

### Where things are

# collections:  null
#   - a_collection

### Filtering Content

future: false

### Serving


### Outputting

timezone: America/Detroit

permalink: date
# paginate: 12
# paginate_path: "/blog/page:num/"

excerpt_separator: "<!-- more -->"
