### Where things are

# collections:  null
#   - a_collection


### Handling Reading

exclude: [vendor, '*org']


### Filtering Content

future: false

### Plugins

# whitelist: []
# gems:      []


### Conversion

markdown: kramdown
excerpt_separator: "<!-- more -->"


### Serving

url: http://wobh.github.io

### Outputting

permalink: date
# paginate: 12
timezone: America/Detroit
